version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.1
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      discovery.type: single-node
    container_name: elasticsearch
